dist: trusty
sudo: required
language: node_js
addons:
  chrome: stable
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
branches:
  only:
  - master
node_js:
- '7'
- '8'
- '9'
script:
- yarn test
- echo "megaman.pomle.com" > build/CNAME
after_success:
- yarn run upload-coverage
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build
  on:
    branch: master
    node: '8'
